#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server
#scp "$buildsource" "$user"@"$ip":"$destination"
StrictHostKeyChecking=no
buildsource="$1"
destination="$0"
ip="$2"
user="$3"

if [ -z "$4" ]
then	
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp "$buildsource" "$user"@"$ip":"$destination"

fi
