#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server
buildsource="$1"
desination="$4"
ip="$2"
user="$3"

if [ -z "$4" ]
then	
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -i "$destination" -o StrictHostKeyChecking=no "$buildsource" "$user"@"$ip":~/

fi
