#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server

if [ "$1" = NULL ] || [ "$2" = NULL ] || [ "$3" = NULL ]
then	
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp some_page.html ubuntu@107.22.144.60:~/

fi

