#!/usr/bin/env bash
# a script that is installing nginx on server
exec { 'apt-get install nginx'
     command => 'apt-get install nginx -y',
     path    => '/usr/bin',
}
file { '/var/www/html/index.html':
    content => 'Hello World!',
  }
