#!/usr/bin/env bash
#this scripts is used to install NGINX
sudo apt-get update
sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
