#!/usr/bin/env bash
# a script that is installing nginx on server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /usr/share/nginx/html/index.html
sudo service nginx restart
