#!/usr/bin/env bash
#this script is customizing NGINX 404 error pqge
sudo apt-get update
sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "<h1>404 Not Found</h1>" | sudo tee /usr/share/nginx/html/custom_404.html
echo "<p>Ceci n'est pas une page</p>" | sudo tee -a /usr/share/nginx/html/custom_404.html
sudo sed -i '/listen 80 default_server;/a error_page 404 /custom_404.html;/nlocation = /custom_404.html {/n/troot /usr/share/nginx/html;/n/tinternal;/n}' /etc/nginx/sites-available/default
sudo service nginx restart
