#!/usr/bin/env bash
# Configure HAProxy load balancer server

apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get -y update
apt-get -y install haproxy=2.6.\*
echo "ENABLED=1" >> /etc/default/haproxy
echo "frontend http
        bind *:80
        mode http
        default_backend web-backend
    backend web-backend
        balance roundrobin
        server 91199-web-01 107.22.144.60:80
        server 91199-web-02 100.24.37.33:80" >> /etc/haproxy/haproxy.cfg

service haproxy restart
