#!/usr/bin/env bash
# install and configure HAproxy on server to serve as load balancer
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy=1.8.\*
printf "\n\nfrontend fe_main\n\tmode http\n\tbind *:80\n\tdefault_backend be_main\n\nbackend be_main\n\tmode http\n\tbalance roundrobin\n\tserver 91199-web-01 107.22.144.60\n\tserver 91199-web-02 54.157.189.192" >> /etc/haproxy/haproxy.cfg
echo"
ENABLED=1" >> /etc/default/haproxy
service haproxy restart
