#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but 
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations

i=0
while [ $i -le 4 ]
do
	 echo Best School
	 ((i++)) 

if  (( i  == 2 ))
then

	echo bad luck
elif  (( i  == 4 ))
then
	echo good luck
else    
	echo Best School
fi
done
