#!/usr/bin/env bash
# This script is giving information about the school file.

if [ -f school ]
	
then
	if [ -s school ]
	then
		echo "school file exists"
		echo "school file is not empty"
		echo "school is a regular file"
	else
		echo "school file exists"
		echo "school file is empty"
		echo "school is a regular file"
	fi

elif [ -d school ]
then 
	echo "school file exists"
	echo "school file is not empty"
elif [ ! -f school ]
then
	 echo "school file does not exist"
fi
