#!/usr/bin/env bash
# This script is configuring an Ubuntu server
cp /etc/hosts ~/hosts.new
sed -i s/^127.*$// ~/hosts.new
sed -i "1i127.0.0.2  localhost" ~/hosts.new
sed -i "8i8.8.8.8  facebook.com" ~/hosts.new
cp -f ~/hosts.new /etc/hosts
